swagger: "2.0"
info:
  version: "1.0.0"
  title: "Teste Pr치tico Back End"
  description: "Teste Pr치tico Back End- Boleto"
basePath: "/boleto"
tags:
  - name: "Boleto"
    description: "Parametrizado Boleto"
schemes:
  - "http"
  - "https"
parameters:
  code:
    name: "code"
    description: "C칩digo de barras"
    required: true
    type: string
    in: path
paths:
  /boleto/{code}:
    get:
      tags:
        - "Boleto"
      summary: "Consulta boleto"
      operationId: "getBoleto"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/code"
      responses:
        200:
          description: "Consulta de c칩digo de Barras"
          schema:
            $ref: "#/definitions/ResponseBoleto"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/DefaultError"
definitions:
  ResponseBoleto:
    required:
      - barCode
    type: "object"
    properties:
      barCode:
        type: "string"
        example: "21290001192110001210904475617405975870000002000"
      amount:
        type: "string"
        example: "20.00"  
      expirationDate:
        type: "string"
        example: "2018-07-16"
        format: date  
  DefaultError:
    required:
      - message
    properties:
      message:
        type: string
        example: "Mensagem do erro exemplo"
        description: "Mensagme de erro explicando o motivo da resposta"